### ISSUE TITLE
kubernetes

### ISSUE THREAD

**Issue by khwerhahn** [Logimethods/docker-jenkins#3]
Hi, 

I'm trying to use this setup within my kubernetes environment. I tried to follow the GCE Jenkins tutorial but run into the `docker` problem. Here is the [Issue](https://github.com/GoogleCloudPlatform/continuous-deployment-on-kubernetes/issues/77) in their  repo. 

I'm a little bit new to k8s, but I have the following the deployment.yaml. How do I tell k8s the initial docker run commands? Maybe this will help someone here.

I get a build error: 
```
+ docker build -t eu.gcr.io/rxxxx/apiservice:master.1 .
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```

```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jenkins
  namespace: jenkins
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
      - name: jenkins
        image: yourJenkinsImageBuildFromDockerfile
        ports:
        - containerPort: 8080
        - containerPort: 50000
        - containerPort: 4040
        readinessProbe:
          httpGet:
            path: /login
            port: 8080
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 2
          failureThreshold: 5
        resources:
          limits:
            cpu: 500m
            memory: 1500Mi
          requests:
            cpu: 500m
            memory: 1500Mi
```
